name: Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pre-Build
        run: |
          gem install cocoapods-acknowledgements
          gem install cocoapods
          pod repo update
          pip install six
          git clone https://github.com/flutter/flutter.git --depth 1 -b beta
          $GITHUB_WORKSPACE/flutter/bin/flutter doctor

      - name: Build
        run: |
          $GITHUB_WORKSPACE/flutter/bin/flutter emulators --launch apple_ios_simulator
          cd $GITHUB_WORKSPACE/example
          $GITHUB_WORKSPACE/flutter/bin/flutter build ios --simulator --no-codesign

      - name: Release
        run: cd $GITHUB_WORKSPACE && bash $GITHUB_WORKSPACE/scripts/deploy.sh
